name: "Nightly publish to nix cache."
on:
  pull_request:
  workflow_dispatch:
  schedule:
        - cron: "0 9 * * *" # 9=9am utc+0

jobs:
  publish-nightly-to-nix-cache:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'roc-lang/roc'
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        skipPush: true  # we only want to push roc_cli
    - uses: cachix/cachix-action@v14
      with:
        name: roc-lang
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: |
        nix build
        nix path-info --json | jq -r 'keys[0]' > temp.txt
        echo "I'm about to upload:"
        cat temp.txt
        echo "Here we go..."
        nix path-info --json | jq -r 'keys[0]' | cachix push roc-lang

  update-commit-log:
    needs: publish-nightly-to-nix-cache
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'roc-lang/roc'

    - name: Get the current commit SHA
      run: echo "CURRENT_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - uses: actions/checkout@v4  # Checkout the current repository
      with:
        path: 'current-repo'
        ref: 'main'

    - name: Append current commit SHA to Roc-commits-in-cache.md
      run: echo "$CURRENT_COMMIT_SHA" >> $GITHUB_WORKSPACE/current-repo/Roc-commits-in-cache.md

    - name: Cut Roc-commits-in-cache.md to 21 lines
      run: tail -n 21 $GITHUB_WORKSPACE/current-repo/Roc-commits-in-cache.md > temp.md && mv temp.md $GITHUB_WORKSPACE/current-repo/Roc-commits-in-cache.md

    - name: Commit and push changes
      run: |
        cd $GITHUB_WORKSPACE/current-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Roc-commits-in-cache.md
        git commit -m "Append roc commit SHA to Roc-commits-in-cache.md"
        git push https://${{ secrets.GH_ACTIONS_PAT }}@github.com/${{ github.repository }} main